### ISSUE TITLE
TuxedoCat compile for Macintosh of Joshua Pettus

### ISSUE THREAD

**Issue by ChessGUI** [nfmccrina/tuxedocat#2]
he made a Mac OS X compiled directory here:
https://www.dropbox.com/s/3syik8qju06tofy/TuxedoCat%20OSX%2010.7%2B.zip?dl=0
(download link), cf.
**Computer Chess Wiki - Macintosh Engine List**
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:macintosh_engine_list

**Comment by nfmccrina** [comment]
Thanks for linking to that, I will add that to the latest release!
